# Spring wweb config
spring.application.name=CRM1640
server.servlet.context-path=/api/v1
server.port = 9999

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5433/Com1640
spring.datasource.username=ThanhThai
spring.datasource.password=meomeo123@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jpa.compliance.proxy=false

# Multipart file config
file.root-path=src/main/java/com/example/CRM1640/images-local
file.temp-folder=/data/app/temp

file.max-size=50MB
file.max-total-size=500MB

file.allowed-types=image/png,image/jpeg,image/webp,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,video/mp4,video/quicktime,video/x-msvideo,video/x-matroska

file.storage-type=local
file.enable-versioning=true
file.keep-days=30
file.encrypt=true 


# ================= MULTIPART =================
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB