# Spring wweb config
spring.application.name=CRM1640
server.servlet.context-path=/api/v1
server.port = 9999

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5433/Com1640
spring.datasource.username=ThanhThai
spring.datasource.password=meomeo123@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jpa.compliance.proxy=false